version: "4.8"

services:
  postgres:
    image: postgres:latest
    container_name: growfuse
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  mailhog:
    image: mailhog/mailhog:latest
    container_name: growuse_mailhog
    ports:
      - "1025:1025" # SMTP server
      - "8025:8025" # Web UI to view emails

  hono:
    image: oven/bun:latest
    container_name: growuse_hono
    working_dir: /app # Set working directory to /src
    volumes:
      - .:/app # Mount the project directory to /src
    command: bun run --hot app.ts # Run the development server with hot reloading
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    env_file:
      - .env

volumes:
  postgres_data:
